[[drone]]
id = 5
connected_node_ids = [1, 7]
pdr = 0.05

[[drone]]
id = 6
connected_node_ids = [1, 2, 7, 8]
pdr = 0.03

[[drone]]
id = 7
connected_node_ids = [4, 5, 6, 9]
pdr = 0.14

[[drone]]
id = 8
connected_node_ids = [3, 6, 9]
pdr = 0.03

[[drone]]
id = 9
connected_node_ids = [3, 4, 7, 8]
pdr = 0.14

[[client]]
id = 1
connected_drone_ids = [5, 6]

[[client]]
id = 2
connected_drone_ids = [6]

[[server]]
id = 3
connected_drone_ids = [8, 9]

[[server]]
id = 4
connected_drone_ids = [7, 9]
