[package]
name = "dn_client"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5.13"
dn_controller = { path = "../dn_controller" }
dn_message = { path = "../dn_message" }
wg_2024 = { git = "https://github.com/WGL-2024/WGL_repo_2024.git" }
petgraph = "0.6.5"
