[package]
name = "dn_controller"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5.13"
petgraph = "0.6.5"
wg_2024 = { git = "https://github.com/WGL-2024/WGL_repo_2024.git" }
dn_message = { path = "../dn_message" }
rayon = "1.10.0"
