name: clippy
on: [ pull_request ]

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  keys:
    steps:
    - name: give gitHub actions access to this repo 
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.REPO_DEPLOY_KEY }}
  clippy:
    needs: keys
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run clippy
        run: cargo clippy --all-targets --all-features
