name: clippy
on: [ pull_request ]

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.REPO_DEPLOY_KEY }}
      - run: git config --global url.ssh://git@github.com/.insteadOf https://github.com/
      - name: run clippy
        run: cargo clippy --all-targets --all-features
