name: rust-fmt 
on: [ pull_request ]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.REPO_DEPLOY_KEY }}
      - run: git config --global url.ssh://git@github.com/.insteadOf https://github.com/
      - name: run cargo fmt
        run: cargo fmt --all --check --quiet
